[tox]
requires = tox >= 4.25.0
env_list = ruff{posargs},clean,typing,py{310,313}-{pyqt5,pyqt6,pyside6}{posargs},report

[testenv]
dependency_groups = test
runner = uv-venv-lock-runner
setenv =
   pyqt5: PYTEST_QT_API=pyqt5
   pyqt6: PYTEST_QT_API=pyqt6
   pyside6: PYTEST_QT_API=pyside6
   COVERAGE_FILE = .coverage.{py_dot_ver}.{env:PYTEST_QT_API}
   QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu"
   QT_QPA_PLATFORM=offscreen
   QT_QUICK_BACKEND=software
   QT_OPENGL=software

[testenv:ruff{,-ci}]
description = run ruff linter
dependency_groups = lint
commands =
   ruff: ruff check
   ruff-ci: ruff check --output-format=github
   ruff format --check
skip_install = true

[testenv:typing]
description = run mypy type checker
dependency_groups = typing
commands = mypy
skip_install = true

[testenv:clean]
description = clean up coverage files
commands = coverage erase
skip_install = true

[testenv:py31{0,3}-{pyqt5,pyqt6,pyside6}]
description = run pytest on python {py_dot_ver}
depends = clean
commands = pytest
extras=
   pyqt5: pyqt5
   pyqt6: pyqt6
   pyside6: pyside6

[testenv:py31{0,3}-{pyqt5,pyqt6,pyside6}-ci]
description = run pytest on python {py_dot_ver}
depends = clean
dependency_groups =
   {[testenv]dependency_groups}
   ci
extras=
   pyqt5: pyqt5
   pyqt6: pyqt6
   pyside6: pyside6
commands =
   pytest
   coveralls
setenv =
   {[testenv]setenv}
   COVERALLS_FLAG_NAME = {on_platform}_python{py_dot_ver}_{env:PYTEST_QT_API}
   COVERALLS_PARALLEL = true
passenv =
   DISPLAY
   XAUTHORITY
   COLUMNS
   GITHUB_*

[testenv:report]
description = combine coverage files
depends = py{310,313}-{pyqt5,pyqt6,pyside6}{posargs}
setenv = COVERAGE_FILE = .coverage
commands = coverage combine
skip_install = true
