name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/documentation.yaml'
      - 'docs/**'
      - 'iblqt/**'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --no-default-groups --group doc --extra pyqt6
      - name: Install libegl1 (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libegl1
          version: 1.0
      - name: Sphinx build
        run: uv run sphinx-build docs/source docs/build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
