name: CI
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: 'pyproject.toml'
          args: 'check --output-format=github'
      - run: 'ruff format --check --diff'

  Testing:
    needs: [Ruff]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --group test
      - name: Install libegl1 (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libegl1
      - name: Run Tests
        run: uv run tox -p auto
      - name: coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          flag-name: ${{ matrix.os }}
          parallel: true
          file: coverage.xml
          compare-ref: main

  Finish:
    needs: [Testing]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
