name: CI
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --no-default-groups --group test --group ci
      - name: Install libegl1 (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libegl1
          version: 1.0
      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run tox --parallel-no-spinner
  finish:
    needs: tox
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
